SET NOCOUNT ON;
SET IDENTITY_INSERT [Lugar] ON; 
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (1, 1, 'Salar de Uyuni', '10:00:00', 'Visita', 2);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (2, 1, 'Isla Incahuasi', '14:00:00', 'Visita', 3);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (3, 2, 'La Paz', '09:00:00', 'Comer', 1);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (4, 2, 'Mercado de las Brujas', '11:00:00', 'Visita', 2);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (5, 3, 'Copacabana', '10:30:00', 'Comer', 1);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (6, 3, 'Isla del Sol', '13:00:00', 'Visita', 3);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (7, 4, 'Potosí', '08:00:00', 'Visita', 2);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (8, 5, 'Sucre', '09:30:00', 'Comer', 1);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (9, 6, 'Tiwanaku', '10:00:00', 'Visita', 2);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (10,7, 'Laguna Verde', '11:00:00', 'Visita', 3);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (11,8, 'Coroico', '09:00:00', 'Comer', 1);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (12,9, 'Yungas', '12:00:00', 'Visita', 2);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (13,10, 'Oruro', '09:30:00', 'Comer', 1);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (14,11, 'Santa Cruz', '10:00:00', 'Visita', 2);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (15,12, 'Parque Nacional Amboró', '11:00:00', 'Visita', 3);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (16,13, 'Rurrenabaque', '12:30:00', 'Visita', 2);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (17,14, 'Madidi', '14:00:00', 'Visita', 3);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (18,15, 'Titicaca', '09:00:00', 'Comer', 1);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (19,16, 'Cochabamba', '10:30:00', 'Visita', 2);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (20,17, 'Valle de la Luna', '11:30:00', 'Visita', 2);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (21,18, 'Tarija', '09:00:00', 'Comer', 1);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (22,19, 'Chacaltaya', '10:00:00', 'Visita', 2);
INSERT INTO [Lugar] ([idLugar],[idRuta], [nombreLugar], [horaPrevistaLlegada], [actividad], [tiempoParadaHoras]) VALUES (23,20, 'Parque Nacional Sajama', '12:00:00', 'Visita', 3);
SET IDENTITY_INSERT [Lugar] OFF;
