SET NOCOUNT ON;
SET IDENTITY_INSERT [Reparacion] ON; 
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (1, 1, 'REP001', 4, 'Cambio de pastillas de freno',120.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (2, 2, 'REP002', 6, 'Ajuste de embrague y revisión del motor',130.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (3, 3, 'REP003', 3, 'Cambio de neumáticos y balanceo',170.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (4, 4, 'REP004', 5, 'Ajuste de suspensión y revisión de frenos',190.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (5, 5, 'REP005', 7, 'Revisión del sistema eléctrico',220.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (6, 6, 'REP006', 8, 'Cambio de aceite y ajuste de motor',320.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (7, 7, 'REP007', 4, 'Cambio de frenos y revisión del sistema de aire',420.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (8, 8, 'REP008', 6, 'Ajuste de dirección y cambio de filtros',150.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (9, 9, 'REP009', 3, 'Cambio de aceite y ajuste de neumáticos',520.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (10,10, 'REP010', 5, 'Revisión de frenos y ajuste de suspensión',20.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (11,11, 'REP011', 6, 'Cambio de frenos y revisión de luces',180.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (12,12, 'REP012', 4, 'Ajuste de suspensión y cambio de aceite',920.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (13,13, 'REP013', 7, 'Revisión del motor y cambio de pastillas de freno',20.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (14,14, 'REP014', 5, 'Ajuste de embrague y cambio de aceite',10.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (15,15, 'REP015', 4, 'Revisión del sistema eléctrico y ajuste de frenos',12.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (16,16, 'REP016', 6, 'Cambio de aceite y ajuste de motor',120.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (17,17, 'REP017', 8, 'Ajuste de suspensión y cambio de neumáticos',220.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (18,18, 'REP018', 5, 'Revisión de frenos y cambio de pastillas',160.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (19,19, 'REP019', 7, 'Ajuste de embrague y revisión del motor',180.00);
INSERT INTO [Reparacion] ([idReparacion],[idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion],[costoReparacion]) VALUES (20,20, 'REP020', 4, 'Cambio de filtros y ajuste de dirección',190.00);
SET IDENTITY_INSERT [Reparacion] OFF;