INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (1, 'REP001', 4, 'Cambio de pastillas de freno');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (2, 'REP002', 6, 'Ajuste de embrague y revisión del motor');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (3, 'REP003', 3, 'Cambio de neumáticos y balanceo');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (4, 'REP004', 5, 'Ajuste de suspensión y revisión de frenos');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (5, 'REP005', 7, 'Revisión del sistema eléctrico');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (6, 'REP006', 8, 'Cambio de aceite y ajuste de motor');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (7, 'REP007', 4, 'Cambio de frenos y revisión del sistema de aire');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (8, 'REP008', 6, 'Ajuste de dirección y cambio de filtros');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (9, 'REP009', 3, 'Cambio de aceite y ajuste de neumáticos');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (10, 'REP010', 5, 'Revisión de frenos y ajuste de suspensión');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (11, 'REP011', 6, 'Cambio de frenos y revisión de luces');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (12, 'REP012', 4, 'Ajuste de suspensión y cambio de aceite');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (13, 'REP013', 7, 'Revisión del motor y cambio de pastillas de freno');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (14, 'REP014', 5, 'Ajuste de embrague y cambio de aceite');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (15, 'REP015', 4, 'Revisión del sistema eléctrico y ajuste de frenos');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (16, 'REP016', 6, 'Cambio de aceite y ajuste de motor');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (17, 'REP017', 8, 'Ajuste de suspensión y cambio de neumáticos');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (18, 'REP018', 5, 'Revisión de frenos y cambio de pastillas');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (19, 'REP019', 7, 'Ajuste de embrague y revisión del motor');
INSERT INTO [Reparacion] ([idRevision], [codigoReparacion], [tiempoEmpleado], [comentarioReparacion]) VALUES (20, 'REP020', 4, 'Cambio de filtros y ajuste de dirección');