INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (1, '2024-01-05', 'Cambio de aceite, revisión de frenos',30.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (2, '2024-02-10', 'Revisión del motor, ajuste de embrague',40.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (3, '2024-03-12', 'Cambio de neumáticos, alineación y balanceo',50.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (4, '2024-04-15', 'Revisión de frenos, ajuste de suspensión',10.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (5, '2024-05-20', 'Cambio de aceite, revisión de luces',12.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (6, '2024-06-25', 'Revisión del sistema eléctrico, ajuste de frenos',20.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (7, '2024-07-30', 'Revisión de motor, cambio de filtros de aire',120.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (8, '2024-08-12', 'Cambio de aceite, ajuste de neumáticos',203.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (9, '2024-09-05', 'Revisión de suspensión, ajuste de frenos',10.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (10, '2024-10-18', 'Cambio de frenos, revisión del sistema de aire',15.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (11, '2024-01-08', 'Revisión del motor, ajuste de dirección',22.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (12, '2024-02-22', 'Cambio de aceite, revisión de neumáticos',20.25);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (13, '2024-03-19', 'Ajuste de frenos, cambio de pastillas',20.10);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (14, '2024-04-27', 'Revisión de luces, ajuste de suspensión',20.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (15, '2024-05-30', 'Cambio de aceite, revisión de frenos',80.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (16, '2024-06-11', 'Revisión del motor, cambio de filtros',70.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (17, '2024-07-25', 'Cambio de neumáticos, alineación y balanceo',120.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (18, '2024-08-20', 'Revisión de frenos, ajuste de suspensión',810.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (19, '2024-09-10', 'Cambio de aceite, revisión de luces',56.00);
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico],[costoRevision]) VALUES (20, '2024-10-15', 'Revisión del sistema eléctrico, ajuste de frenos',76.00);