INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (1, '2024-01-05', 'Cambio de aceite, revisión de frenos');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (2, '2024-02-10', 'Revisión del motor, ajuste de embrague');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (3, '2024-03-12', 'Cambio de neumáticos, alineación y balanceo');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (4, '2024-04-15', 'Revisión de frenos, ajuste de suspensión');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (5, '2024-05-20', 'Cambio de aceite, revisión de luces');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (6, '2024-06-25', 'Revisión del sistema eléctrico, ajuste de frenos');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (7, '2024-07-30', 'Revisión de motor, cambio de filtros de aire');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (8, '2024-08-12', 'Cambio de aceite, ajuste de neumáticos');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (9, '2024-09-05', 'Revisión de suspensión, ajuste de frenos');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (10, '2024-10-18', 'Cambio de frenos, revisión del sistema de aire');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (11, '2024-01-08', 'Revisión del motor, ajuste de dirección');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (12, '2024-02-22', 'Cambio de aceite, revisión de neumáticos');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (13, '2024-03-19', 'Ajuste de frenos, cambio de pastillas');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (14, '2024-04-27', 'Revisión de luces, ajuste de suspensión');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (15, '2024-05-30', 'Cambio de aceite, revisión de frenos');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (16, '2024-06-11', 'Revisión del motor, cambio de filtros');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (17, '2024-07-25', 'Cambio de neumáticos, alineación y balanceo');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (18, '2024-08-20', 'Revisión de frenos, ajuste de suspensión');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (19, '2024-09-10', 'Cambio de aceite, revisión de luces');
INSERT INTO [Revision] ([idAutobus], [fechaRevision], [diagnostico]) VALUES (20, '2024-10-15', 'Revisión del sistema eléctrico, ajuste de frenos');