INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta La Paz - Oruro', 150.50, 5, 1, 210.45);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Santa Cruz - Cochabamba', 175.30, 6, 1, 300.75);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Sucre - Potosí', 90.20, 3, 1, 154.32);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta La Paz - Santa Cruz', 250.75, 10, 1, 489.50);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Tarija - Sucre', 160.80, 8, 1, 320.75);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Cochabamba - Oruro', 120.60, 4, 1, 195.67);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Potosí - Uyuni', 80.50, 3, 1, 110.12);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Trinidad - Santa Cruz', 210.90, 9, 1, 420.78);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Cobija - Riberalta', 185.40, 7, 1, 350.22);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta La Paz - Sucre', 190.25, 11, 1, 460.15);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Cochabamba - Tarija', 220.85, 12, 1, 478.23);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Santa Cruz - Potosí', 195.50, 9, 1, 365.34);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Oruro - Potosí', 110.75, 5, 1, 180.25);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Cochabamba - Sucre', 145.35, 6, 1, 310.45);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Tarija - Potosí', 170.40, 8, 1, 325.67);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Riberalta - Trinidad', 190.90, 7, 1, 280.34);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Uyuni - Potosí', 105.80, 4, 1, 130.50);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta La Paz - Cochabamba', 175.95, 7, 1, 370.22);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Santa Cruz - Oruro', 180.40, 8, 1, 400.90);
INSERT INTO [dbo].[Ruta] (nombreRuta, importe, duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Potosí - Sucre', 85.60, 3, 1, 145.30);
