INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta La Paz - Oruro', 5, 1, 210.45);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Santa Cruz - Cochabamba', 6, 1, 300.75);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Sucre - Potosí', 3, 1, 154.32);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta La Paz - Santa Cruz', 10, 1, 489.50);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Tarija - Sucre', 8, 1, 320.75);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Cochabamba - Oruro', 4, 1, 195.67);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Potosí - Uyuni', 3, 1, 110.12);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Trinidad - Santa Cruz', 9, 1, 420.78);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Cobija - Riberalta', 7, 1, 350.22);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta La Paz - Sucre', 11, 1, 460.15);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Cochabamba - Tarija', 12, 1, 478.23);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Santa Cruz - Potosí', 9, 1, 365.34);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Oruro - Potosí', 5, 1, 180.25);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Cochabamba - Sucre', 6, 1, 310.45);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Tarija - Potosí', 8, 1, 325.67);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Riberalta - Trinidad', 7, 1, 280.34);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Uyuni - Potosí', 4, 1, 130.50);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta La Paz - Cochabamba', 7, 1, 370.22);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Santa Cruz - Oruro', 8, 1, 400.90);
INSERT INTO [dbo].[Ruta] (nombreRuta,  duracionAproximadaHoras, esMasAtractiva, kilometrosRecorrido) VALUES ('Ruta Potosí - Sucre', 3, 1, 145.30);
