:r .\clean.data.sql
:r .\Turista.data.sql
:r .\Ruta.data.sql
:r .\Conductor.data.sql
:r .\Autobus.data.sql
:r .\Revision.data.sql
:r .\Reparacion.data.sql
:r .\Lugar.data.sql
:r .\Servicio.data.sql
:r .\Viaje.data.sql
:r .\Boleto.data.sql
:r .\Compra.data.sql